<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>Project-AgentGate-V</AssemblyName>
    <RootNamespace>ProjectAgentGateV</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <ApplicationIcon>Assets\Project-AgentGate-V.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.ML.OnnxRuntime.DirectML" Version="1.24.4" />
    <PackageReference Include="System.Management" Version="8.0.0" />
    <PackageReference Include="System.Drawing.Common" Version="8.0.31" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Assets\Project-AgentGate-V.ico" />
    <Resource Include="Assets\and-gate-spritesheet.png" />
    <EmbeddedResource Include="Assets\fpga_net.onnx" LogicalName="ProjectAgentGateV.Assets.fpga_net.onnx" />
  </ItemGroup>
</Project>
